// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/pkg/email (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=email -destination=pkg/email/email_mock.go hasir-api/pkg/email Service
//

// Package email is a generated GoMock package.
package email

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SendInvite mocks base method.
func (m *MockService) SendInvite(to, organizationName, inviteToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvite", to, organizationName, inviteToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvite indicates an expected call of SendInvite.
func (mr *MockServiceMockRecorder) SendInvite(to, organizationName, inviteToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvite", reflect.TypeOf((*MockService)(nil).SendInvite), to, organizationName, inviteToken)
}
