// Code generated by MockGen. DO NOT EDIT.
// Source: apps/api/internal/repository (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=repository -destination=internal/repository/service_mock.go apps/api/internal/repository Service
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	repositoryv1 "buf.build/gen/go/hasir/hasir/protocolbuffers/go/repository/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *MockService) CreateRepository(ctx context.Context, req *repositoryv1.CreateRepositoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockServiceMockRecorder) CreateRepository(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockService)(nil).CreateRepository), ctx, req)
}
