// Code generated by MockGen. DO NOT EDIT.
// Source: apps/api/internal/organization (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=organization -destination=internal/organization/repository_mock.go apps/api/internal/organization Repository
//

// Package organization is a generated GoMock package.
package organization

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockRepository) CreateOrganization(ctx context.Context, org *OrganizationDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockRepositoryMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockRepository)(nil).CreateOrganization), ctx, org)
}

// GetOrganizationByName mocks base method.
func (m *MockRepository) GetOrganizationByName(ctx context.Context, name string) (*OrganizationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByName", ctx, name)
	ret0, _ := ret[0].(*OrganizationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByName indicates an expected call of GetOrganizationByName.
func (mr *MockRepositoryMockRecorder) GetOrganizationByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByName", reflect.TypeOf((*MockRepository)(nil).GetOrganizationByName), ctx, name)
}

// GetOrganizations mocks base method.
func (m *MockRepository) GetOrganizations(ctx context.Context) (*[]OrganizationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizations", ctx)
	ret0, _ := ret[0].(*[]OrganizationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizations indicates an expected call of GetOrganizations.
func (mr *MockRepositoryMockRecorder) GetOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizations", reflect.TypeOf((*MockRepository)(nil).GetOrganizations), ctx)
}
