// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/organization (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=organization -destination=internal/organization/repository_mock.go hasir-api/internal/organization Repository
//

// Package organization is a generated GoMock package.
package organization

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockRepository) AddMember(ctx context.Context, member *OrganizationMemberDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockRepositoryMockRecorder) AddMember(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockRepository)(nil).AddMember), ctx, member)
}

// CreateInvite mocks base method.
func (m *MockRepository) CreateInvite(ctx context.Context, invite *OrganizationInviteDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockRepositoryMockRecorder) CreateInvite(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockRepository)(nil).CreateInvite), ctx, invite)
}

// CreateOrganization mocks base method.
func (m *MockRepository) CreateOrganization(ctx context.Context, org *OrganizationDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockRepositoryMockRecorder) CreateOrganization(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockRepository)(nil).CreateOrganization), ctx, org)
}

// GetInviteByToken mocks base method.
func (m *MockRepository) GetInviteByToken(ctx context.Context, token string) (*OrganizationInviteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteByToken", ctx, token)
	ret0, _ := ret[0].(*OrganizationInviteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteByToken indicates an expected call of GetInviteByToken.
func (mr *MockRepositoryMockRecorder) GetInviteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteByToken", reflect.TypeOf((*MockRepository)(nil).GetInviteByToken), ctx, token)
}

// GetOrganizationById mocks base method.
func (m *MockRepository) GetOrganizationById(ctx context.Context, id string) (*OrganizationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationById", ctx, id)
	ret0, _ := ret[0].(*OrganizationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationById indicates an expected call of GetOrganizationById.
func (mr *MockRepositoryMockRecorder) GetOrganizationById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationById", reflect.TypeOf((*MockRepository)(nil).GetOrganizationById), ctx, id)
}

// GetOrganizationByName mocks base method.
func (m *MockRepository) GetOrganizationByName(ctx context.Context, name string) (*OrganizationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByName", ctx, name)
	ret0, _ := ret[0].(*OrganizationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByName indicates an expected call of GetOrganizationByName.
func (mr *MockRepositoryMockRecorder) GetOrganizationByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByName", reflect.TypeOf((*MockRepository)(nil).GetOrganizationByName), ctx, name)
}

// GetOrganizations mocks base method.
func (m *MockRepository) GetOrganizations(ctx context.Context, page, pageSize int) (*[]OrganizationDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizations", ctx, page, pageSize)
	ret0, _ := ret[0].(*[]OrganizationDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizations indicates an expected call of GetOrganizations.
func (mr *MockRepositoryMockRecorder) GetOrganizations(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizations", reflect.TypeOf((*MockRepository)(nil).GetOrganizations), ctx, page, pageSize)
}

// GetOrganizationsCount mocks base method.
func (m *MockRepository) GetOrganizationsCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationsCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationsCount indicates an expected call of GetOrganizationsCount.
func (mr *MockRepositoryMockRecorder) GetOrganizationsCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationsCount", reflect.TypeOf((*MockRepository)(nil).GetOrganizationsCount), ctx)
}

// UpdateInviteStatus mocks base method.
func (m *MockRepository) UpdateInviteStatus(ctx context.Context, id string, status InviteStatus, acceptedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInviteStatus", ctx, id, status, acceptedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInviteStatus indicates an expected call of UpdateInviteStatus.
func (mr *MockRepositoryMockRecorder) UpdateInviteStatus(ctx, id, status, acceptedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInviteStatus", reflect.TypeOf((*MockRepository)(nil).UpdateInviteStatus), ctx, id, status, acceptedAt)
}
