// Code generated by MockGen. DO NOT EDIT.
// Source: apps/api/internal/organization (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=organization -destination=internal/organization/service_mock.go apps/api/internal/organization Service
//

// Package organization is a generated GoMock package.
package organization

import (
	context "context"
	reflect "reflect"

	organizationv1 "buf.build/gen/go/hasir/hasir/protocolbuffers/go/organization/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockService) CreateOrganization(ctx context.Context, req *organizationv1.CreateOrganizationRequest, createdBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, req, createdBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockServiceMockRecorder) CreateOrganization(ctx, req, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockService)(nil).CreateOrganization), ctx, req, createdBy)
}

// RespondToInvitation mocks base method.
func (m *MockService) RespondToInvitation(ctx context.Context, token, userId string, accept bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToInvitation", ctx, token, userId, accept)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondToInvitation indicates an expected call of RespondToInvitation.
func (mr *MockServiceMockRecorder) RespondToInvitation(ctx, token, userId, accept any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToInvitation", reflect.TypeOf((*MockService)(nil).RespondToInvitation), ctx, token, userId, accept)
}
