// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/organization (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=organization -destination=internal/organization/service_mock.go hasir-api/internal/organization Service
//

// Package organization is a generated GoMock package.
package organization

import (
	context "context"
	reflect "reflect"

	organizationv1 "buf.build/gen/go/hasir/hasir/protocolbuffers/go/organization/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockService) CreateOrganization(ctx context.Context, req *organizationv1.CreateOrganizationRequest, createdBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, req, createdBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockServiceMockRecorder) CreateOrganization(ctx, req, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockService)(nil).CreateOrganization), ctx, req, createdBy)
}

// DeleteMember mocks base method.
func (m *MockService) DeleteMember(ctx context.Context, req *organizationv1.DeleteMemberRequest, deletedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", ctx, req, deletedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *MockServiceMockRecorder) DeleteMember(ctx, req, deletedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockService)(nil).DeleteMember), ctx, req, deletedBy)
}

// DeleteOrganization mocks base method.
func (m *MockService) DeleteOrganization(ctx context.Context, organizationId, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, organizationId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockServiceMockRecorder) DeleteOrganization(ctx, organizationId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockService)(nil).DeleteOrganization), ctx, organizationId, userId)
}

// InviteUser mocks base method.
func (m *MockService) InviteUser(ctx context.Context, req *organizationv1.InviteMemberRequest, invitedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteUser", ctx, req, invitedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteUser indicates an expected call of InviteUser.
func (mr *MockServiceMockRecorder) InviteUser(ctx, req, invitedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteUser", reflect.TypeOf((*MockService)(nil).InviteUser), ctx, req, invitedBy)
}

// RespondToInvitation mocks base method.
func (m *MockService) RespondToInvitation(ctx context.Context, token, userId string, accept bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToInvitation", ctx, token, userId, accept)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondToInvitation indicates an expected call of RespondToInvitation.
func (mr *MockServiceMockRecorder) RespondToInvitation(ctx, token, userId, accept any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToInvitation", reflect.TypeOf((*MockService)(nil).RespondToInvitation), ctx, token, userId, accept)
}

// UpdateMemberRole mocks base method.
func (m *MockService) UpdateMemberRole(ctx context.Context, req *organizationv1.UpdateMemberRoleRequest, updatedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", ctx, req, updatedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockServiceMockRecorder) UpdateMemberRole(ctx, req, updatedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockService)(nil).UpdateMemberRole), ctx, req, updatedBy)
}

// UpdateOrganization mocks base method.
func (m *MockService) UpdateOrganization(ctx context.Context, req *organizationv1.UpdateOrganizationRequest, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, req, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockServiceMockRecorder) UpdateOrganization(ctx, req, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockService)(nil).UpdateOrganization), ctx, req, userId)
}
