// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/registry (interfaces: SdkGenerationQueue)
//
// Generated by this command:
//
//	mockgen -package=registry -destination=internal/registry/queue_mock.go hasir-api/internal/registry SdkGenerationQueue
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSdkGenerationQueue is a mock of SdkGenerationQueue interface.
type MockSdkGenerationQueue struct {
	ctrl     *gomock.Controller
	recorder *MockSdkGenerationQueueMockRecorder
	isgomock struct{}
}

// MockSdkGenerationQueueMockRecorder is the mock recorder for MockSdkGenerationQueue.
type MockSdkGenerationQueueMockRecorder struct {
	mock *MockSdkGenerationQueue
}

// NewMockSdkGenerationQueue creates a new mock instance.
func NewMockSdkGenerationQueue(ctrl *gomock.Controller) *MockSdkGenerationQueue {
	mock := &MockSdkGenerationQueue{ctrl: ctrl}
	mock.recorder = &MockSdkGenerationQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSdkGenerationQueue) EXPECT() *MockSdkGenerationQueueMockRecorder {
	return m.recorder
}

// EnqueueSdkGenerationJobs mocks base method.
func (m *MockSdkGenerationQueue) EnqueueSdkGenerationJobs(ctx context.Context, jobs []*SdkGenerationJobDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueSdkGenerationJobs", ctx, jobs)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueSdkGenerationJobs indicates an expected call of EnqueueSdkGenerationJobs.
func (mr *MockSdkGenerationQueueMockRecorder) EnqueueSdkGenerationJobs(ctx, jobs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueSdkGenerationJobs", reflect.TypeOf((*MockSdkGenerationQueue)(nil).EnqueueSdkGenerationJobs), ctx, jobs)
}

// GetPendingSdkGenerationJobs mocks base method.
func (m *MockSdkGenerationQueue) GetPendingSdkGenerationJobs(ctx context.Context, limit int) ([]*SdkGenerationJobDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSdkGenerationJobs", ctx, limit)
	ret0, _ := ret[0].([]*SdkGenerationJobDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingSdkGenerationJobs indicates an expected call of GetPendingSdkGenerationJobs.
func (mr *MockSdkGenerationQueueMockRecorder) GetPendingSdkGenerationJobs(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSdkGenerationJobs", reflect.TypeOf((*MockSdkGenerationQueue)(nil).GetPendingSdkGenerationJobs), ctx, limit)
}

// Start mocks base method.
func (m *MockSdkGenerationQueue) Start(ctx context.Context, sdkGenerator SdkGenerator, batchSize int, pollInterval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, sdkGenerator, batchSize, pollInterval)
}

// Start indicates an expected call of Start.
func (mr *MockSdkGenerationQueueMockRecorder) Start(ctx, sdkGenerator, batchSize, pollInterval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSdkGenerationQueue)(nil).Start), ctx, sdkGenerator, batchSize, pollInterval)
}

// Stop mocks base method.
func (m *MockSdkGenerationQueue) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSdkGenerationQueueMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSdkGenerationQueue)(nil).Stop))
}

// UpdateSdkGenerationJobStatus mocks base method.
func (m *MockSdkGenerationQueue) UpdateSdkGenerationJobStatus(ctx context.Context, jobId string, status SdkGenerationJobStatus, errorMsg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSdkGenerationJobStatus", ctx, jobId, status, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSdkGenerationJobStatus indicates an expected call of UpdateSdkGenerationJobStatus.
func (mr *MockSdkGenerationQueueMockRecorder) UpdateSdkGenerationJobStatus(ctx, jobId, status, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSdkGenerationJobStatus", reflect.TypeOf((*MockSdkGenerationQueue)(nil).UpdateSdkGenerationJobStatus), ctx, jobId, status, errorMsg)
}
