// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/registry (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=registry -destination=internal/registry/repository_mock.go hasir-api/internal/registry Repository
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"

	registryv1 "buf.build/gen/go/hasir/hasir/protocolbuffers/go/registry/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *MockRepository) CreateRepository(ctx context.Context, repo *RepositoryDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockRepositoryMockRecorder) CreateRepository(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockRepository)(nil).CreateRepository), ctx, repo)
}

// DeleteRepositoriesByOrganizationId mocks base method.
func (m *MockRepository) DeleteRepositoriesByOrganizationId(ctx context.Context, organizationId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepositoriesByOrganizationId", ctx, organizationId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepositoriesByOrganizationId indicates an expected call of DeleteRepositoriesByOrganizationId.
func (mr *MockRepositoryMockRecorder) DeleteRepositoriesByOrganizationId(ctx, organizationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepositoriesByOrganizationId", reflect.TypeOf((*MockRepository)(nil).DeleteRepositoriesByOrganizationId), ctx, organizationId)
}

// DeleteRepository mocks base method.
func (m *MockRepository) DeleteRepository(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepository", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepository indicates an expected call of DeleteRepository.
func (mr *MockRepositoryMockRecorder) DeleteRepository(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepository", reflect.TypeOf((*MockRepository)(nil).DeleteRepository), ctx, id)
}

// GetCommits mocks base method.
func (m *MockRepository) GetCommits(ctx context.Context, repoPath string) (*registryv1.GetCommitsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommits", ctx, repoPath)
	ret0, _ := ret[0].(*registryv1.GetCommitsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommits indicates an expected call of GetCommits.
func (mr *MockRepositoryMockRecorder) GetCommits(ctx, repoPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommits", reflect.TypeOf((*MockRepository)(nil).GetCommits), ctx, repoPath)
}

// GetFilePreview mocks base method.
func (m *MockRepository) GetFilePreview(ctx context.Context, repoPath, filePath string) (*registryv1.GetFilePreviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePreview", ctx, repoPath, filePath)
	ret0, _ := ret[0].(*registryv1.GetFilePreviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePreview indicates an expected call of GetFilePreview.
func (mr *MockRepositoryMockRecorder) GetFilePreview(ctx, repoPath, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePreview", reflect.TypeOf((*MockRepository)(nil).GetFilePreview), ctx, repoPath, filePath)
}

// GetFileTree mocks base method.
func (m *MockRepository) GetFileTree(ctx context.Context, repoPath string, subPath *string) (*registryv1.GetFileTreeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileTree", ctx, repoPath, subPath)
	ret0, _ := ret[0].(*registryv1.GetFileTreeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileTree indicates an expected call of GetFileTree.
func (mr *MockRepositoryMockRecorder) GetFileTree(ctx, repoPath, subPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileTree", reflect.TypeOf((*MockRepository)(nil).GetFileTree), ctx, repoPath, subPath)
}

// GetRepositories mocks base method.
func (m *MockRepository) GetRepositories(ctx context.Context, page, pageSize int) (*[]RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositories", ctx, page, pageSize)
	ret0, _ := ret[0].(*[]RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositories indicates an expected call of GetRepositories.
func (mr *MockRepositoryMockRecorder) GetRepositories(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositories", reflect.TypeOf((*MockRepository)(nil).GetRepositories), ctx, page, pageSize)
}

// GetRepositoriesByOrganizationId mocks base method.
func (m *MockRepository) GetRepositoriesByOrganizationId(ctx context.Context, organizationId string) (*[]RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesByOrganizationId", ctx, organizationId)
	ret0, _ := ret[0].(*[]RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesByOrganizationId indicates an expected call of GetRepositoriesByOrganizationId.
func (mr *MockRepositoryMockRecorder) GetRepositoriesByOrganizationId(ctx, organizationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesByOrganizationId", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesByOrganizationId), ctx, organizationId)
}

// GetRepositoriesByUser mocks base method.
func (m *MockRepository) GetRepositoriesByUser(ctx context.Context, userId string, page, pageSize int) (*[]RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesByUser", ctx, userId, page, pageSize)
	ret0, _ := ret[0].(*[]RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesByUser indicates an expected call of GetRepositoriesByUser.
func (mr *MockRepositoryMockRecorder) GetRepositoriesByUser(ctx, userId, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesByUser", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesByUser), ctx, userId, page, pageSize)
}

// GetRepositoriesByUserAndOrganization mocks base method.
func (m *MockRepository) GetRepositoriesByUserAndOrganization(ctx context.Context, userId, organizationId string, page, pageSize int) (*[]RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesByUserAndOrganization", ctx, userId, organizationId, page, pageSize)
	ret0, _ := ret[0].(*[]RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesByUserAndOrganization indicates an expected call of GetRepositoriesByUserAndOrganization.
func (mr *MockRepositoryMockRecorder) GetRepositoriesByUserAndOrganization(ctx, userId, organizationId, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesByUserAndOrganization", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesByUserAndOrganization), ctx, userId, organizationId, page, pageSize)
}

// GetRepositoriesByUserAndOrganizationCount mocks base method.
func (m *MockRepository) GetRepositoriesByUserAndOrganizationCount(ctx context.Context, userId, organizationId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesByUserAndOrganizationCount", ctx, userId, organizationId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesByUserAndOrganizationCount indicates an expected call of GetRepositoriesByUserAndOrganizationCount.
func (mr *MockRepositoryMockRecorder) GetRepositoriesByUserAndOrganizationCount(ctx, userId, organizationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesByUserAndOrganizationCount", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesByUserAndOrganizationCount), ctx, userId, organizationId)
}

// GetRepositoriesByUserCount mocks base method.
func (m *MockRepository) GetRepositoriesByUserCount(ctx context.Context, userId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesByUserCount", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesByUserCount indicates an expected call of GetRepositoriesByUserCount.
func (mr *MockRepositoryMockRecorder) GetRepositoriesByUserCount(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesByUserCount", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesByUserCount), ctx, userId)
}

// GetRepositoryById mocks base method.
func (m *MockRepository) GetRepositoryById(ctx context.Context, id string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryById", ctx, id)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryById indicates an expected call of GetRepositoryById.
func (mr *MockRepositoryMockRecorder) GetRepositoryById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryById", reflect.TypeOf((*MockRepository)(nil).GetRepositoryById), ctx, id)
}

// GetRepositoryByName mocks base method.
func (m *MockRepository) GetRepositoryByName(ctx context.Context, name string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByName", ctx, name)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByName indicates an expected call of GetRepositoryByName.
func (mr *MockRepositoryMockRecorder) GetRepositoryByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByName", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByName), ctx, name)
}

// GetSdkPreferences mocks base method.
func (m *MockRepository) GetSdkPreferences(ctx context.Context, repositoryId string) ([]SdkPreferencesDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSdkPreferences", ctx, repositoryId)
	ret0, _ := ret[0].([]SdkPreferencesDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSdkPreferences indicates an expected call of GetSdkPreferences.
func (mr *MockRepositoryMockRecorder) GetSdkPreferences(ctx, repositoryId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSdkPreferences", reflect.TypeOf((*MockRepository)(nil).GetSdkPreferences), ctx, repositoryId)
}

// GetSdkPreferencesByRepositoryIds mocks base method.
func (m *MockRepository) GetSdkPreferencesByRepositoryIds(ctx context.Context, repositoryIds []string) (map[string][]SdkPreferencesDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSdkPreferencesByRepositoryIds", ctx, repositoryIds)
	ret0, _ := ret[0].(map[string][]SdkPreferencesDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSdkPreferencesByRepositoryIds indicates an expected call of GetSdkPreferencesByRepositoryIds.
func (mr *MockRepositoryMockRecorder) GetSdkPreferencesByRepositoryIds(ctx, repositoryIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSdkPreferencesByRepositoryIds", reflect.TypeOf((*MockRepository)(nil).GetSdkPreferencesByRepositoryIds), ctx, repositoryIds)
}

// UpdateRepository mocks base method.
func (m *MockRepository) UpdateRepository(ctx context.Context, repo *RepositoryDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepository indicates an expected call of UpdateRepository.
func (mr *MockRepositoryMockRecorder) UpdateRepository(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepository", reflect.TypeOf((*MockRepository)(nil).UpdateRepository), ctx, repo)
}

// UpdateSdkPreferences mocks base method.
func (m *MockRepository) UpdateSdkPreferences(ctx context.Context, repositoryId string, preferences []SdkPreferencesDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSdkPreferences", ctx, repositoryId, preferences)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSdkPreferences indicates an expected call of UpdateSdkPreferences.
func (mr *MockRepositoryMockRecorder) UpdateSdkPreferences(ctx, repositoryId, preferences any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSdkPreferences", reflect.TypeOf((*MockRepository)(nil).UpdateSdkPreferences), ctx, repositoryId, preferences)
}
