// Code generated by MockGen. DO NOT EDIT.
// Source: internal/registry/repository.go

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddCollaborator mocks base method.
func (m *MockRepository) AddCollaborator(ctx context.Context, collaborator *RepositoryCollaboratorDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollaborator", ctx, collaborator)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollaborator indicates an expected call of AddCollaborator.
func (mr *MockRepositoryMockRecorder) AddCollaborator(ctx, collaborator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollaborator", reflect.TypeOf((*MockRepository)(nil).AddCollaborator), ctx, collaborator)
}

// CheckRepositoryAccess mocks base method.
func (m *MockRepository) CheckRepositoryAccess(ctx context.Context, username, owner, repoName, accessType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRepositoryAccess", ctx, username, owner, repoName, accessType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRepositoryAccess indicates an expected call of CheckRepositoryAccess.
func (mr *MockRepositoryMockRecorder) CheckRepositoryAccess(ctx, username, owner, repoName, accessType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRepositoryAccess", reflect.TypeOf((*MockRepository)(nil).CheckRepositoryAccess), ctx, username, owner, repoName, accessType)
}

// CreateRepository mocks base method.
func (m *MockRepository) CreateRepository(ctx context.Context, repo *RepositoryDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockRepositoryMockRecorder) CreateRepository(ctx, repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockRepository)(nil).CreateRepository), ctx, repo)
}

// GetCollaboratorPermission mocks base method.
func (m *MockRepository) GetCollaboratorPermission(ctx context.Context, repoId, userId string) (*CollaboratorPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollaboratorPermission", ctx, repoId, userId)
	ret0, _ := ret[0].(*CollaboratorPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollaboratorPermission indicates an expected call of GetCollaboratorPermission.
func (mr *MockRepositoryMockRecorder) GetCollaboratorPermission(ctx, repoId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollaboratorPermission", reflect.TypeOf((*MockRepository)(nil).GetCollaboratorPermission), ctx, repoId, userId)
}

// GetCollaborators mocks base method.
func (m *MockRepository) GetCollaborators(ctx context.Context, repoId string) ([]*RepositoryCollaboratorDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollaborators", ctx, repoId)
	ret0, _ := ret[0].([]*RepositoryCollaboratorDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollaborators indicates an expected call of GetCollaborators.
func (mr *MockRepositoryMockRecorder) GetCollaborators(ctx, repoId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollaborators", reflect.TypeOf((*MockRepository)(nil).GetCollaborators), ctx, repoId)
}

// GetRepositories mocks base method.
func (m *MockRepository) GetRepositories(ctx context.Context, page, pageSize int) (*[]RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositories", ctx, page, pageSize)
	ret0, _ := ret[0].(*[]RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositories indicates an expected call of GetRepositories.
func (mr *MockRepositoryMockRecorder) GetRepositories(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositories", reflect.TypeOf((*MockRepository)(nil).GetRepositories), ctx, page, pageSize)
}

// GetRepositoriesCount mocks base method.
func (m *MockRepository) GetRepositoriesCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesCount indicates an expected call of GetRepositoriesCount.
func (mr *MockRepositoryMockRecorder) GetRepositoriesCount(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesCount", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesCount), ctx)
}

// GetRepositoryById mocks base method.
func (m *MockRepository) GetRepositoryById(ctx context.Context, id string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryById", ctx, id)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryById indicates an expected call of GetRepositoryById.
func (mr *MockRepositoryMockRecorder) GetRepositoryById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryById", reflect.TypeOf((*MockRepository)(nil).GetRepositoryById), ctx, id)
}

// GetRepositoryByName mocks base method.
func (m *MockRepository) GetRepositoryByName(ctx context.Context, name string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByName", ctx, name)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByName indicates an expected call of GetRepositoryByName.
func (mr *MockRepositoryMockRecorder) GetRepositoryByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByName", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByName), ctx, name)
}

// GetRepositoryByPath mocks base method.
func (m *MockRepository) GetRepositoryByPath(ctx context.Context, owner, name string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByPath", ctx, owner, name)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByPath indicates an expected call of GetRepositoryByPath.
func (mr *MockRepositoryMockRecorder) GetRepositoryByPath(ctx, owner, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByPath", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByPath), ctx, owner, name)
}

// RemoveCollaborator mocks base method.
func (m *MockRepository) RemoveCollaborator(ctx context.Context, repoId, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCollaborator", ctx, repoId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCollaborator indicates an expected call of RemoveCollaborator.
func (mr *MockRepositoryMockRecorder) RemoveCollaborator(ctx, repoId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCollaborator", reflect.TypeOf((*MockRepository)(nil).RemoveCollaborator), ctx, repoId, userId)
}
