// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/registry (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=registry -destination=internal/registry/repository_mock.go hasir-api/internal/registry Repository
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *MockRepository) CreateRepository(ctx context.Context, repo *RepositoryDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockRepositoryMockRecorder) CreateRepository(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockRepository)(nil).CreateRepository), ctx, repo)
}

// DeleteRepository mocks base method.
func (m *MockRepository) DeleteRepository(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepository", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepository indicates an expected call of DeleteRepository.
func (mr *MockRepositoryMockRecorder) DeleteRepository(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepository", reflect.TypeOf((*MockRepository)(nil).DeleteRepository), ctx, id)
}

// GetRepositories mocks base method.
func (m *MockRepository) GetRepositories(ctx context.Context, page, pageSize int) (*[]RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositories", ctx, page, pageSize)
	ret0, _ := ret[0].(*[]RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositories indicates an expected call of GetRepositories.
func (mr *MockRepositoryMockRecorder) GetRepositories(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositories", reflect.TypeOf((*MockRepository)(nil).GetRepositories), ctx, page, pageSize)
}

// GetRepositoriesCount mocks base method.
func (m *MockRepository) GetRepositoriesCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoriesCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoriesCount indicates an expected call of GetRepositoriesCount.
func (mr *MockRepositoryMockRecorder) GetRepositoriesCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoriesCount", reflect.TypeOf((*MockRepository)(nil).GetRepositoriesCount), ctx)
}

// GetRepositoryById mocks base method.
func (m *MockRepository) GetRepositoryById(ctx context.Context, id string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryById", ctx, id)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryById indicates an expected call of GetRepositoryById.
func (mr *MockRepositoryMockRecorder) GetRepositoryById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryById", reflect.TypeOf((*MockRepository)(nil).GetRepositoryById), ctx, id)
}

// GetRepositoryByName mocks base method.
func (m *MockRepository) GetRepositoryByName(ctx context.Context, name string) (*RepositoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByName", ctx, name)
	ret0, _ := ret[0].(*RepositoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByName indicates an expected call of GetRepositoryByName.
func (mr *MockRepositoryMockRecorder) GetRepositoryByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByName", reflect.TypeOf((*MockRepository)(nil).GetRepositoryByName), ctx, name)
}

// UpdateRepository mocks base method.
func (m *MockRepository) UpdateRepository(ctx context.Context, repo *RepositoryDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepository", ctx, repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepository indicates an expected call of UpdateRepository.
func (mr *MockRepositoryMockRecorder) UpdateRepository(ctx, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepository", reflect.TypeOf((*MockRepository)(nil).UpdateRepository), ctx, repo)
}
