// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/registry (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=registry -destination=internal/registry/service_mock.go hasir-api/internal/registry Service
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"

	registryv1 "buf.build/gen/go/hasir/hasir/protocolbuffers/go/registry/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateRepository mocks base method.
func (m *MockService) CreateRepository(ctx context.Context, req *registryv1.CreateRepositoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepository", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRepository indicates an expected call of CreateRepository.
func (mr *MockServiceMockRecorder) CreateRepository(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepository", reflect.TypeOf((*MockService)(nil).CreateRepository), ctx, req)
}

// DeleteRepositoriesByOrganization mocks base method.
func (m *MockService) DeleteRepositoriesByOrganization(ctx context.Context, organizationId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepositoriesByOrganization", ctx, organizationId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepositoriesByOrganization indicates an expected call of DeleteRepositoriesByOrganization.
func (mr *MockServiceMockRecorder) DeleteRepositoriesByOrganization(ctx, organizationId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepositoriesByOrganization", reflect.TypeOf((*MockService)(nil).DeleteRepositoriesByOrganization), ctx, organizationId)
}

// DeleteRepository mocks base method.
func (m *MockService) DeleteRepository(ctx context.Context, req *registryv1.DeleteRepositoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepository", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepository indicates an expected call of DeleteRepository.
func (mr *MockServiceMockRecorder) DeleteRepository(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepository", reflect.TypeOf((*MockService)(nil).DeleteRepository), ctx, req)
}

// GetCommits mocks base method.
func (m *MockService) GetCommits(ctx context.Context, req *registryv1.GetCommitsRequest) (*registryv1.GetCommitsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommits", ctx, req)
	ret0, _ := ret[0].(*registryv1.GetCommitsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommits indicates an expected call of GetCommits.
func (mr *MockServiceMockRecorder) GetCommits(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommits", reflect.TypeOf((*MockService)(nil).GetCommits), ctx, req)
}

// GetFilePreview mocks base method.
func (m *MockService) GetFilePreview(ctx context.Context, req *registryv1.GetFilePreviewRequest) (*registryv1.GetFilePreviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePreview", ctx, req)
	ret0, _ := ret[0].(*registryv1.GetFilePreviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePreview indicates an expected call of GetFilePreview.
func (mr *MockServiceMockRecorder) GetFilePreview(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePreview", reflect.TypeOf((*MockService)(nil).GetFilePreview), ctx, req)
}

// GetFileTree mocks base method.
func (m *MockService) GetFileTree(ctx context.Context, req *registryv1.GetFileTreeRequest) (*registryv1.GetFileTreeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileTree", ctx, req)
	ret0, _ := ret[0].(*registryv1.GetFileTreeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileTree indicates an expected call of GetFileTree.
func (mr *MockServiceMockRecorder) GetFileTree(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileTree", reflect.TypeOf((*MockService)(nil).GetFileTree), ctx, req)
}

// GetRepositories mocks base method.
func (m *MockService) GetRepositories(ctx context.Context, organizationId *string, page, pageSize int) (*registryv1.GetRepositoriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositories", ctx, organizationId, page, pageSize)
	ret0, _ := ret[0].(*registryv1.GetRepositoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositories indicates an expected call of GetRepositories.
func (mr *MockServiceMockRecorder) GetRepositories(ctx, organizationId, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositories", reflect.TypeOf((*MockService)(nil).GetRepositories), ctx, organizationId, page, pageSize)
}

// GetRepository mocks base method.
func (m *MockService) GetRepository(ctx context.Context, req *registryv1.GetRepositoryRequest) (*registryv1.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository", ctx, req)
	ret0, _ := ret[0].(*registryv1.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockServiceMockRecorder) GetRepository(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockService)(nil).GetRepository), ctx, req)
}

// UpdateRepository mocks base method.
func (m *MockService) UpdateRepository(ctx context.Context, req *registryv1.UpdateRepositoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepository", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepository indicates an expected call of UpdateRepository.
func (mr *MockServiceMockRecorder) UpdateRepository(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepository", reflect.TypeOf((*MockService)(nil).UpdateRepository), ctx, req)
}

// UpdateSdkPreferences mocks base method.
func (m *MockService) UpdateSdkPreferences(ctx context.Context, req *registryv1.UpdateSdkPreferencesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSdkPreferences", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSdkPreferences indicates an expected call of UpdateSdkPreferences.
func (mr *MockServiceMockRecorder) UpdateSdkPreferences(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSdkPreferences", reflect.TypeOf((*MockService)(nil).UpdateSdkPreferences), ctx, req)
}

// ValidateSshAccess mocks base method.
func (m *MockService) ValidateSshAccess(ctx context.Context, userId, repoPath string, operation SshOperation) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSshAccess", ctx, userId, repoPath, operation)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSshAccess indicates an expected call of ValidateSshAccess.
func (mr *MockServiceMockRecorder) ValidateSshAccess(ctx, userId, repoPath, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSshAccess", reflect.TypeOf((*MockService)(nil).ValidateSshAccess), ctx, userId, repoPath, operation)
}
