// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/internal/user (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package=user -destination=internal/user/repository_mock.go hasir-api/internal/user Repository
//

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateApiKey mocks base method.
func (m *MockRepository) CreateApiKey(ctx context.Context, userId, name, apiKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", ctx, userId, name, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockRepositoryMockRecorder) CreateApiKey(ctx, userId, name, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockRepository)(nil).CreateApiKey), ctx, userId, name, apiKey)
}

// CreateRefreshToken mocks base method.
func (m *MockRepository) CreateRefreshToken(ctx context.Context, id, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, id, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockRepositoryMockRecorder) CreateRefreshToken(ctx, id, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockRepository)(nil).CreateRefreshToken), ctx, id, token, expiresAt)
}

// CreateSshKey mocks base method.
func (m *MockRepository) CreateSshKey(ctx context.Context, userId, name, publicKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSshKey", ctx, userId, name, publicKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSshKey indicates an expected call of CreateSshKey.
func (mr *MockRepositoryMockRecorder) CreateSshKey(ctx, userId, name, publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSshKey", reflect.TypeOf((*MockRepository)(nil).CreateSshKey), ctx, userId, name, publicKey)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, user *UserDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, user)
}

// DeleteRefreshToken mocks base method.
func (m *MockRepository) DeleteRefreshToken(ctx context.Context, userId, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, userId, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockRepositoryMockRecorder) DeleteRefreshToken(ctx, userId, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockRepository)(nil).DeleteRefreshToken), ctx, userId, token)
}

// DeleteUser mocks base method.
func (m *MockRepository) DeleteUser(ctx context.Context, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockRepositoryMockRecorder) DeleteUser(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRepository)(nil).DeleteUser), ctx, userId)
}

// GetApiKeys mocks base method.
func (m *MockRepository) GetApiKeys(ctx context.Context, userId string, page, pageSize int) (*[]ApiKeyDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeys", ctx, userId, page, pageSize)
	ret0, _ := ret[0].(*[]ApiKeyDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeys indicates an expected call of GetApiKeys.
func (mr *MockRepositoryMockRecorder) GetApiKeys(ctx, userId, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeys", reflect.TypeOf((*MockRepository)(nil).GetApiKeys), ctx, userId, page, pageSize)
}

// GetApiKeysCount mocks base method.
func (m *MockRepository) GetApiKeysCount(ctx context.Context, userId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeysCount", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeysCount indicates an expected call of GetApiKeysCount.
func (mr *MockRepositoryMockRecorder) GetApiKeysCount(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeysCount", reflect.TypeOf((*MockRepository)(nil).GetApiKeysCount), ctx, userId)
}

// GetRefreshTokenByTokenId mocks base method.
func (m *MockRepository) GetRefreshTokenByTokenId(ctx context.Context, token string) (*RefreshTokensDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByTokenId", ctx, token)
	ret0, _ := ret[0].(*RefreshTokensDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByTokenId indicates an expected call of GetRefreshTokenByTokenId.
func (mr *MockRepositoryMockRecorder) GetRefreshTokenByTokenId(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByTokenId", reflect.TypeOf((*MockRepository)(nil).GetRefreshTokenByTokenId), ctx, token)
}

// GetSshKeys mocks base method.
func (m *MockRepository) GetSshKeys(ctx context.Context, userId string, page, pageSize int) (*[]SshKeyDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSshKeys", ctx, userId, page, pageSize)
	ret0, _ := ret[0].(*[]SshKeyDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSshKeys indicates an expected call of GetSshKeys.
func (mr *MockRepositoryMockRecorder) GetSshKeys(ctx, userId, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSshKeys", reflect.TypeOf((*MockRepository)(nil).GetSshKeys), ctx, userId, page, pageSize)
}

// GetSshKeysCount mocks base method.
func (m *MockRepository) GetSshKeysCount(ctx context.Context, userId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSshKeysCount", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSshKeysCount indicates an expected call of GetSshKeysCount.
func (mr *MockRepositoryMockRecorder) GetSshKeysCount(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSshKeysCount", reflect.TypeOf((*MockRepository)(nil).GetSshKeysCount), ctx, userId)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserById mocks base method.
func (m *MockRepository) GetUserById(ctx context.Context, id string) (*UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(*UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockRepositoryMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockRepository)(nil).GetUserById), ctx, id)
}

// GetUsersByEmails mocks base method.
func (m *MockRepository) GetUsersByEmails(ctx context.Context, emails []string) (map[string]*UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByEmails", ctx, emails)
	ret0, _ := ret[0].(map[string]*UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByEmails indicates an expected call of GetUsersByEmails.
func (mr *MockRepositoryMockRecorder) GetUsersByEmails(ctx, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByEmails", reflect.TypeOf((*MockRepository)(nil).GetUsersByEmails), ctx, emails)
}

// RevokeApiKey mocks base method.
func (m *MockRepository) RevokeApiKey(ctx context.Context, userId, keyId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeApiKey", ctx, userId, keyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeApiKey indicates an expected call of RevokeApiKey.
func (mr *MockRepositoryMockRecorder) RevokeApiKey(ctx, userId, keyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeApiKey", reflect.TypeOf((*MockRepository)(nil).RevokeApiKey), ctx, userId, keyId)
}

// RevokeSshKey mocks base method.
func (m *MockRepository) RevokeSshKey(ctx context.Context, userId, keyId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSshKey", ctx, userId, keyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSshKey indicates an expected call of RevokeSshKey.
func (mr *MockRepositoryMockRecorder) RevokeSshKey(ctx, userId, keyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSshKey", reflect.TypeOf((*MockRepository)(nil).RevokeSshKey), ctx, userId, keyId)
}

// UpdateUserById mocks base method.
func (m *MockRepository) UpdateUserById(ctx context.Context, id string, user *UserDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserById", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserById indicates an expected call of UpdateUserById.
func (mr *MockRepositoryMockRecorder) UpdateUserById(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserById", reflect.TypeOf((*MockRepository)(nil).UpdateUserById), ctx, id, user)
}
