// Code generated by MockGen. DO NOT EDIT.
// Source: hasir-api/pkg/organization (interfaces: MemberRoleChecker)
//
// Generated by this command:
//
//	mockgen -package=organization -destination=pkg/organization/authorization_mock.go hasir-api/pkg/organization MemberRoleChecker
//

// Package organization is a generated GoMock package.
package organization

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMemberRoleChecker is a mock of MemberRoleChecker interface.
type MockMemberRoleChecker struct {
	ctrl     *gomock.Controller
	recorder *MockMemberRoleCheckerMockRecorder
	isgomock struct{}
}

// MockMemberRoleCheckerMockRecorder is the mock recorder for MockMemberRoleChecker.
type MockMemberRoleCheckerMockRecorder struct {
	mock *MockMemberRoleChecker
}

// NewMockMemberRoleChecker creates a new mock instance.
func NewMockMemberRoleChecker(ctrl *gomock.Controller) *MockMemberRoleChecker {
	mock := &MockMemberRoleChecker{ctrl: ctrl}
	mock.recorder = &MockMemberRoleCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberRoleChecker) EXPECT() *MockMemberRoleCheckerMockRecorder {
	return m.recorder
}

// GetMemberRole mocks base method.
func (m *MockMemberRoleChecker) GetMemberRole(ctx context.Context, organizationId, userId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", ctx, organizationId, userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockMemberRoleCheckerMockRecorder) GetMemberRole(ctx, organizationId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockMemberRoleChecker)(nil).GetMemberRole), ctx, organizationId, userId)
}
